// Mock data for offline development when internet is unavailable
export const mockStudents = [
  {
    id: '1',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john@example.com',
    phone: '021 1234567',
    school_id: '1',
    grade: 'Grade 3',
    enrollment_status: 'active',
    payment_status: 'paid',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    invoice_sent: false,
    cubing_competition_invited: false,
    parent_notes: null,
    schools: {
      id: '1',
      name: 'Example Primary School',
      target_enrollment: 30,
      current_enrollment: 15,
      monthly_cost: 2500,
      program_fee_per_student: 450,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  },
  {
    id: '2',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane@example.com',
    phone: '021 7654321',
    school_id: '1',
    grade: 'Grade 4',
    enrollment_status: 'active',
    payment_status: 'outstanding',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    invoice_sent: true,
    cubing_competition_invited: false,
    parent_notes: 'Excellent progress',
    schools: {
      id: '1',
      name: 'Example Primary School',
      target_enrollment: 30,
      current_enrollment: 15,
      monthly_cost: 2500,
      program_fee_per_student: 450,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  },
  {
    id: '3',
    first_name: 'Michael',
    last_name: 'Johnson',
    email: 'michael@example.com',
    phone: '021 5555555',
    school_id: '2',
    grade: 'Grade 5',
    enrollment_status: 'active',
    payment_status: 'paid',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    invoice_sent: false,
    cubing_competition_invited: true,
    parent_notes: null,
    schools: {
      id: '2',
      name: 'Bright Star Secondary',
      target_enrollment: 50,
      current_enrollment: 25,
      monthly_cost: 3500,
      program_fee_per_student: 550,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  }
]

export const mockSchools = [
  {
    id: '1',
    name: 'Example Primary School',
    target_enrollment: 30,
    current_enrollment: 15,
    monthly_cost: 2500,
    program_fee_per_student: 450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bright Star Secondary',
    target_enrollment: 50,
    current_enrollment: 25,
    monthly_cost: 3500,
    program_fee_per_student: 550,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Central High School',
    target_enrollment: 60,
    current_enrollment: 40,
    monthly_cost: 4000,
    program_fee_per_student: 600,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
]
